---
- hosts: idrac
  connection: local
  name: Setup default NTP SMTP SNMP
  gather_facts: False

  vars:
    idrac_ip: "{{ baseuri }}"
    idrac_user: "{{ username }}"
    idrac_password: "{{ password }}"
  tasks:
    - name: Configure the iDRAC attributes for SMTP alert settings.
      dellemc.openmanage.idrac_attributes:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
      validate_certs: no
      idrac_attributes:
        RemoteHosts.1.SMTPServerIPAddress: "{{ smtp_ipaddress }}"
        RemoteHosts.1.SMTPAuthentication: "{{ smtp_auth }}"
        RemoteHosts.1.SMTPPort: "{{ smtp_port }}"
        RemoteHosts.1.SMTPUserName: "{{ smtp_user }}"
        RemoteHosts.1.SMTPPassword: "{{ smtp_pass }}"
