---
- name: config SNMP
  hosts: idrac
  connection: local
  tasks:
    - name: Configure SNMP community string, port, protocol and trap format
      community.general.idrac_redfish_config:
        category: Manager
        command: SetManagerAttributes
        resource_id: iDRAC.Embedded.1
        manager_attributes:
          SNMP.1.AgentEnable: Enabled
          SNMP.1.AgentCommunity: public_community_string
          SNMP.1.TrapFormat: SNMPv1
          SNMP.1.SNMPProtocol: All
          SNMP.1.DiscoveryPort: 161
          SNMP.1.AlertPort: 162
        baseuri: "{{ baseuri }}"
        username: "{{ username}}"
        password: "{{ password }}"

