- name: firmware update
  hosts: idrac
  connection: local
  gather_facts: false

  vars:
    image_url: "http://10.10.20.134/firmware/iDRAC-with-Lifecycle-Controller_Firmware_FGR4H_WN64_7.20.30.55_A00.EXE"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Send firmware update request
      community.general.redfish_command:
        category: Update
        command: SimpleUpdate
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        update_image_uri: "{{ image_url }}"
        validate_certs: false
