---
- name: Dell iDRAC Power Control via Redfish
  hosts: idrac
  connection: local
  gather_facts: false
  vars:
    resource_id: "System.Embedded.1"   # ส่วนมาก Dell ใช้อันนี้แทน serial number
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Ensure playbook is run with tag
      fail:
        msg: "You must run this playbook with a tag! Example: ansible-playbook site.yml --tags [graceful_restart][force_off][force_restart][graceful_shutdown][power_on][reboot]"
      when: ansible_run_tags | length == 2
      tags:
        - always
