---
- name: Get all iDRAC attributes
  hosts: idrac
  connection: local
  gather_facts: false
  vars:
    idrac_ip: "{{ baseuri }}"
    idrac_user: "{{ username }}"
    idrac_password: "{{ password }}"
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: View iDRAC attributes
      dellemc.openmanage.idrac_attributes:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        idrac_attributes: {}
        validate_certs: no  
      register: idrac_attr

    - debug:
        var: idrac_attr

