---
- name: Check and update Dell firmware if version is different
  hosts: idrac
  connection: local
  gather_facts: no
  vars:
    idrac_ip: "{{ baseuri }}"
    idrac_user: "{{ username }}"
    idrac_password: "{{ password }}"
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Get current firmware info
      dellemc.openmanage.idrac_firmware_info:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        validate_certs: no
      register: fw_info

    - name: Set current version fact
      set_fact:
        current_version: "{{ (fw_info.firmware_info | selectattr('name','search', firmware_name) | list)[0].version }}"

    - name: Show versions
      debug:
        msg: "Current {{ firmware_name }} version: {{ current_version }}"

