- name: firmware update (safe)
  hosts: idrac
  connection: local
  gather_facts: false

  vars:
    image_url: "http://10.10.20.134/firmware/BIOS_0HY8N_WN64_1.17.2.EXE"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Send firmware update request
      community.general.redfish_command:
        category: Update
        command: SimpleUpdate
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        update_image_uri: "{{ image_url }}"
        validate_certs: false

