- name: Test fake firmware update (safe)
  hosts: idrac
  connection: local
  gather_facts: false

  vars:
    image_url: "http://dl.dell.com/FOLDER13373971M/1/iDRAC_7.20.30.55_A00.exe"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Send firmware update request
      community.general.redfish_command:
        category: Update
        command: SimpleUpdate
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        update_image_uri: "{{ image_url }}"
        validate_certs: false
