---
- name: Create RAID 1 Virtual Disk via Redfish
  hosts: idrac
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    idrac_ip: "{{ baseuri }}"
    idrac_user: "{{ username }}"
    idrac_password: "{{ password }}"
    virtual_disk_name: "RAID_say_hi"
    controller_id: "RAID.SL.3-1"

    # <<== ใส่แค่ชื่อ disk แบบย่อได้ที่นี่
    drive_ids:
      - "Disk.Bay.0:Enclosure.Internal.0-1:RAID.SL.3-1"
      - "Disk.Bay.1:Enclosure.Internal.0-1:RAID.SL.3-1"

  tasks:
    - name: สร้างลิสต์ @odata.id ที่ถูกต้อง
      set_fact:
        drives: []

    - name: แปลงชื่อ drive_ids ให้เป็น path
      set_fact:
        drives: "{{ drives + [ { '@odata.id': '/redfish/v1/Systems/System.Embedded.1/Storage/' ~ controller_id ~ '/Drives/' ~ item } ] }}"
      loop: "{{ drive_ids }}"

    - name: Create RAID 1 virtual disk
      uri:
        url: "https://{{ idrac_ip }}/redfish/v1/Systems/System.Embedded.1/Storage/{{ controller_id }}/Volumes"
        method: POST
        user: "{{ idrac_user }}"
        password: "{{ idrac_password }}"
        force_basic_auth: yes
        validate_certs: no
        status_code: [200, 202]
        headers:
          Content-Type: application/json
        body_format: json
        body:
          Name: "{{ virtual_disk_name }}"
          RAIDType: "RAID1"
          Drives: "{{ drives }}"
      register: result

    - name: Show result
      debug:
        var: result

