---
- name: Configure iDRAC SMTP
  hosts: localhost
  gather_facts: false
  vars:
    idrac_ip: "10.10.40.240"
    idrac_user: "root"
    idrac_password: "calvin!"
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    sender_email: "idrac-alerts@yourdomain.com"
    recipient_email: "admin@yourdomain.com"
    smtp_password: "your_app_password"  # สำหรับ Gmail ใช้ App Password

  tasks:
    - name: Install Dell EMC Collection (หากยังไม่ได้ติดตั้ง)
      ansible.builtin.command: ansible-galaxy collection install dellemc.openmanage
      changed_when: false

    - name: Configure SMTP
      dellemc.openmanage.idrac_smtp:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
        smtp_server: "{{ smtp_server }}"
        smtp_port: "{{ smtp_port }}"
        smtp_username: "{{ sender_email }}"
        smtp_password: "{{ smtp_password }}"
        alert_email: "{{ recipient_email }}"
        smtp_authentication: "enabled"
        smtp_ssl: "enabled"
      delegate_to: localhost
      no_log: true
